services:
  todo-database:
    image: mongo:latest
    container_name: todo-database
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: michvel
      MONGO_INITDB_ROOT_PASSWORD: 0O1vV5XArcZtYHz9
    networks:
      - node-network

  backend:
    build: ./server
    container_name: backend
    ports:
      - "5500:5500"
    depends_on:
      - todo-database
      - minio
    environment:
      DATABASE_URL: mongodb+srv://michvel:0O1vV5XArcZtYHz9@cluster0.cn9jvzg.mongodb.net/todoApp?authSource=admin
      MINIO_URL: "minio:9000"
      JWT_SECRET: "michvel"
    volumes:
      - ./backend:/usr/src/app
    networks:
      - node-network
    command: node index.js

  frontend:
    build: ./client/todo
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL="http://backend:5500"
    volumes:
      - ./frontend:/src/app

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "miniopassword"
      MINIO_DEFAULT_BUCKETS: "firsts3trial"
      MINIO_REGION: "eu-north-1"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  mongo-data:
  minio-data:

networks:
  node-network:
    driver: bridge
