version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_ROOT_USERNAME: michvel
      MONGO_ROOT_PASSWORD: 0O1vV5XArcZtYHz9

  backend:
    build: ./server
    container_name: backend
    ports:
      - "4500:4500"
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: "mongodb+srv://michvel:0O1vV5XArcZtYHz9@cluster0.cn9jvzg.mongodb.net/todoApp?authSource=admin"
      JWT_SECRET: "michvel"
    volumes:
      - ./backend:/usr/src/app
    command: nodemon index.js

  frontend:
    build: ./client/todo
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/src/app

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER_KEY: "IA5DE4VSFWWLIHKNX2"
      MINIO_ROOT_PASSWORD: "U6peb5aw4brPoueKAV3C0/ESQwejb28dGESN3qYg"
      MINIO_DEFAULT_BUCKETS: "firsts3trial"
      MINIO_REGION: "eu-north-1"
    command: server /data
    volumes:
      - minio-data:/data

volumes:
  mongo-data:
  minio-data:
